<h1>Multi-classes Logistic Regression methode2 V0.0.ipynb</h1>

In [2]:
import numpy as np
import random



class LogisticRegression:
    def __init__(self, X:np.array, y:np.array, alpha:float = 0.01, n_iteration:int = 10000, tolerance:float = 0.1):
        self.y_pred = np.empty(X.shape[0])
        self.w = np.random.rand(X.shape[1], y.shape[1])
        self.b = np.random.rand(y.shape[1])
        self.alpha = alpha
        self.n_iteration = n_iteration
        self.tolerance = tolerance
        
        
    def softmax(self, X):
        z = X@self.w + self.b
        soft = np.exp(z)/np.sum(np.exp(z), axis = 1)[:,None]
        return soft
                
    def fit(self, X, y):
        iteration = 0
        precision = np.inf
        n = len(y)
        while precision > self.tolerance and iteration < self.n_iteration:
            z = self.softmax(X)
            dw = (1/n)*X.T@(z - y)
            db = (1/n)*sum(z - y)
            self.w -= self.alpha*dw
            self.b -= self.alpha*db
            precision = np.max(abs(sum(y*np.log(z))))
            iteration += 1
        return self.w, self.b, precision, dw, db

    def predict(self, X):
        z = self.softmax(X)
        self.y_pred = np.argmax(z, axis = 1)
        return self.y_pred

    def accuracy(self, y, y_pred):
        y = np.argmax(y, axis = 1)
        return 100*(sum(np.array(y == y_pred))/len(y)).round(2)

def main():
    global X, y, model, dw, db, precision
    '''
    X = np.random.randint(0,10, size = (100,3))
    y = np.array(random.choices(['a', 'b', 'c'], k = X.shape[0]))
    '''

    from sklearn.datasets import load_iris
    data = load_iris()
    X = data.data
    y = data.target

    from sklearn.preprocessing import OneHotEncoder
    enc = OneHotEncoder(sparse_output = False)
    y = enc.fit_transform(y.reshape(-1, 1))

    from sklearn.preprocessing import StandardScaler
    enc = StandardScaler()
    X = enc.fit_transform(X)

    from sklearn.model_selection import train_test_split
    x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=0)
    
    model = LogisticRegression(x_train, y_train)
    
    w, b, precision, dw, db = model.fit(x_train, y_train)
    print(f'model: \nw = {w} \nb= {b}\n')
    print('x_test = ', x_test, '\n')
    print('y_test_encoded = ', y_test, '\n')
    print('y_test = ', np.argmax(y_test, axis = 1), '\n')
    y_pred = model.predict(x_test)
    print(f'y_pred = {model.y_pred}\n')
    
    print(f'accuracy : {model.accuracy(y_test, model.y_pred)}, %')
    

if __name__ == '__main__':
    main()

model: 
w = [[-0.83151989  0.97185736  0.95880569]
 [ 1.55164256 -0.23142491 -0.52249688]
 [-1.66280534  0.41585082  2.57300726]
 [-1.39268976 -0.32921788  3.40996032]] 
b= [-0.099996    2.4522364  -1.08569939]

x_test =  [[-5.25060772e-02 -5.92373012e-01  7.62758269e-01  1.58046376e+00]
 [ 1.89829664e-01 -1.97355361e+00  1.37546573e-01 -2.62386821e-01]
 [-4.16009689e-01  2.63038172e+00 -1.34022653e+00 -1.31544430e+00]
 [ 1.76501198e+00 -3.62176246e-01  1.44480739e+00  7.90670654e-01]
 [-1.02184904e+00  7.88807586e-01 -1.28338910e+00 -1.31544430e+00]
 [ 5.53333275e-01  5.58610819e-01  1.27429511e+00  1.71209594e+00]
 [-1.02184904e+00  1.01900435e+00 -1.39706395e+00 -1.18381211e+00]
 [ 1.03800476e+00  9.82172869e-02  5.35408562e-01  3.95774101e-01]
 [ 1.15917263e+00 -5.92373012e-01  5.92245988e-01  2.64141916e-01]
 [ 3.10997534e-01 -5.92373012e-01  1.37546573e-01  1.32509732e-01]
 [ 3.10997534e-01 -1.05276654e+00  1.04694540e+00  2.64141916e-01]
 [ 6.74501145e-01  3.28414053e-01  4.2173